### ISSUE TITLE
[scripts] Rework travis automation so we can run again

### ISSUE THREAD

**Issue by rufuspollock** [datasets/s-and-p-500-companies#25]
We want to rework travis automation so we can run again
* [ ] only commit and push if a change in data
* [ ] push to github
* [ ] push to datahub

## Acceptance criteria

* [ ] only commit and push if a change in data
  * [ ] push to GitHub
  * [ ] publish to DataHub

## Tasks

* [ ] refactor `travis.yml` since it is outdated
* [ ] add publishing to DataHub

## Analysis

After trying to run a script, there are a bunch of libraries are outdated. For example, `datapackage-py`, `goodtables-py` and so on. And test script on `scripts/test_data.py` is not working. 
I suggest to remove this test script or to write something else.

For the DataHub part we can add this snipped which runs only on `deploy` part
```
language: node_js
node_js:
- '8'
install:
- npm install -g git+https://github.com/datahq/datahub-cli.git
script: data push ./ --published
env:
  global:
    id: core
    username: core
  TRAVIS_SECURE_ENV_VARS: true
```
Using travis configuration, we can add `token` env.variable

**Comment by rufuspollock** [comment]
INVALID (Obsolete).
